name: Test And Deploy
on: 
  push:
jobs:
  test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          echo {{secrets.DEPLOY_CREDENTIALS}} > .secrets.json
          npm i
          install -g truffle

      - name: deploy
        run: truffle migrate --network kovan

        