name: Test And Deploy
on: 
  push:

env: 
    MNEMONIC: ${{secrets.MNEMONIC}}
    PROJECT_ID: ${{secrets.PROJECT_ID}}
jobs:
  test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install node dependencies
        run: |
          npm i
          npm i -g truffle
          npm i -g ganache-cli

      - name: install python dependencies
        run: |
          pip install pytest
          pip install web3
          pip install py-solc-x
          pip install bitcoin
          pip install python-bitcoinlib 
          pip install tqdm
          
      - name: deploy
        run: truffle migrate --network kovan


      - name: Basic Smoke test
        run: npm test 

      - name: Test storage vs memory
        run: |
          ganache-cli -p 7545 &
          cd tests 
          sleep 5
          pytest -v -s storage_vs_memory.py && echo "test finished. see results and warnings above."
          

        