name: Test And Deploy
on: 
  push:

env: 
    MNEMONIC: ${{secrets.MNEMONIC}}
    PROJECT_ID: ${{secrets.PROJECT_ID}}
jobs:
  test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install dependencies
        run: |
          npm i
          npm i -g truffle

      - name: deploy
        run: truffle migrate --network kovan


      - name: test
        run: npm test 

        